### ISSUE TITLE
end-to-end visual demo

### ISSUE THREAD

**Issue by jameslamb** [uptake/numpynet#12]
I think this project would benefit from an end-to-end demo that allows someone to pull up, on their local machine, a visual tool such as [visdom](https://github.com/facebookresearch/visdom), try to kick off a training run on a toy problem, and watch that training run in their browser.

Ideally, this example would be copy-paste code (either pure script calls or some Dockerized app call) that could serve as a "Quickstart" example.

**Comment by bburns632** [comment]
@mairuoliu, all yours!

**Comment by bburns632** [comment]
Thank you for #48!
